services:
  db:
    image: postgres:16-alpine
    container_name: sisinove_shared_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "127.0.0.1:5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- SISDIP ---
  sisdip_backend:
    build: ./backend
    restart: always
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/sisdip?schema=public
      PORT: 4001
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:8081
    ports:
      - "127.0.0.1:4001:4001"

  sisdip_frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4001/api
    ports:
      - "127.0.0.1:8081:5173"
    command: sh -c "npm install && npm run dev -- --host --port 5173"

  # --- ISO ---
  iso_backend:
    build: ../sisinove-iso/backend
    restart: always
    env_file: ../sisinove-iso/.env
    volumes:
      - ../sisinove-iso/backend:/app
      - /app/node_modules
      - ../sisinove-iso/backend/uploads:/app/uploads:Z
    environment:
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/sisinove_iso?schema=public
      PORT: 4000
    ports:
      - "127.0.0.1:4000:4000"

  iso_frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../sisinove-iso/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:4000/api
    ports:
      - "127.0.0.1:8082:5173" # Mapeia a porta 8082 local para a 5173 do Vite
    # Adicionamos o comando para rodar o dev server do ISO
    command: sh -c "npm install && npm run dev -- --host --port 5173"

volumes:
  postgres_data:
